theme: jekyll-theme-slate

# Site settings
title: You Blog    				  	#你博客的标题
SEOTitle: 你的博客 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/background.jpg  	#显示在首页的背景图片
email: yuhangxiaocs@gmail.com	
description: "share knowledge"  			 #网站介绍
keyword: "algorithm, design, software, machine learning" #关键词
url: "https://yuhangxiaocs.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
